import 'package:hello_world_app/models/food.dart';

const List<Food> dummyFoods = [
  Food(
    id: 1,
    name: 'Crispy Burger',
    price: 12.99,
    rating: 4.8,
    description: 'Juicy grilled beef with melted cheese and tangy sauce.',
    image: 'assets/food/burger.svg',
    category: 'Burgers',
    deliveryTime: '20 min',
  ),
  Food(
    id: 2,
    name: 'Garden Pizza',
    price: 14.5,
    rating: 4.7,
    description: 'Hand-tossed pizza with roasted vegetables and herb drizzle.',
    image: 'assets/food/pizza.svg',
    category: 'Pizza',
    deliveryTime: '25 min',
  ),
  Food(
    id: 3,
    name: 'Fresh Pasta',
    price: 13.25,
    rating: 4.9,
    description: 'Creamy pasta with basil, parmesan and roasted garlic.',
    image: 'assets/food/pasta.svg',
    category: 'Pasta',
    deliveryTime: '18 min',
  ),
  Food(
    id: 4,
    name: 'Sushi Delight',
    price: 16.0,
    rating: 4.6,
    description: 'Fresh sushi rolls with sesame and wasabi cucumber.',
    image: 'assets/food/sushi.svg',
    category: 'Sushi',
    deliveryTime: '30 min',
  ),
  Food(
    id: 5,
    name: 'Summer Bowl',
    price: 10.75,
    rating: 4.5,
    description: 'Bright grains, greens and grilled chicken in a light bowl.',
    image: 'assets/food/bowl.svg',
    category: 'Bowls',
    deliveryTime: '15 min',
  ),
];
